#!/bin/bash

build() {
    local mod
    for mod in dm-mod dm-snapshot dm-mirror dm-cache dm-cache-mq; do
        add_module "$mod"
    done

    add_binary "/sbin/lvm"
    add_binary "/sbin/lvmetad"
    add_binary "/sbin/dmsetup"
    add_binary "/sbin/cache_check"
    add_binary "/sbin/cache_dump"
    add_binary "/sbin/cache_metadata_size"
    add_binary "/sbin/cache_repair"
    add_binary "/sbin/cache_restore"
    add_file "/lib/udev/rules.d/10-dm.rules"
    add_file "/lib/udev/rules.d/13-dm-disk.rules"
    add_file "/lib/udev/rules.d/95-dm-notify.rules"
    add_file "/lib/udev/rules.d/11-dm-lvm.rules"
    add_file "/lib/initcpio/udev/69-dm-lvm-metad.rules" "/lib/udev/rules.d/69-dm-lvm-metad.rules"
    add_file "/lib/initcpio/udev/11-dm-initramfs.rules" "/lib/udev/rules.d/11-dm-initramfs.rules"
    add_file "/etc/lvm/lvm.conf"

    # add a link of all gcc runtime libs the thin provisioning tools need
    LIBCPP_PATH=$(tail -n1 /etc/ld.so.conf.d/05gcc-x86_64-pc-linux-gnu.conf)

    for i in $BUILDROOT/$LIBCPP_PATH/* ; do
       local fn=$(basename $i)
       add_symlink "/usr/lib/$fn" "$LIBCPP_PATH/$fn"
    done
    #

    add_runscript
}

help() {
  cat <<HELPEOF
This hook enables LVM2 volumes in initramfs.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
