#! /bin/sh
COLLECT_LTO_WRAPPER="$(gcc -v |& grep COLLECT_LTO | cut -d= -f2)"
LTO_PLUGIN_DIR=${COLLECT_LTO_WRAPPER%/lto-wrapper}

touch /tmp/ranlib

exec /usr/bin/ranlib $command --plugin $LTO_PLUGIN_DIR/liblto_plugin.so $*
