#!/bin/sh
svc_dir="$1"

function log() {
   #echo "lusi-unit-generator: $*"  >> /tmp/lusi-log.txt
   #echo "lusi-unit-generator: $*"  > /dev/kmesg
   #logger "lusi-unit-generator: $*"
   true
}

function mp_to_unitbn() {
   where="$1"
   if [ "$where" = "/" ]; then
      echo -
   else
      echo ${where#/} | sed -e 's:-:\\x2d:g' -e 's:/:-:g'
   fi
}

function mk_automount_unit() {
   # automatically called from mk_mount_unit
   local what="$1"
   local where="$2"
   local target="$3"
   local unit_bn=$(mp_to_unitbn $where)

   cat << EOF > "${svc_dir}/${unit_bn}.automount"
[Unit]
Description=automount unit for $what
Documentation=file:///usr/lib/systemd/system-generators/dema-automount-generator
Before=$target

[Automount]
Where=$where
EOF
}

function mk_mount_unit() {
   local what="$1"
   local where="$2"
   local fs="$3"
   local opts="$4"
   local unit_bn=$(mp_to_unitbn $where)

   if [ "${fs#nfs}" != "$fs" ] ; then
      local target="remote-fs.target"
   else
      local target="local-fs.target"
   fi

   if [ -z "$(echo $opts | grep x-systemd.automount)" ] ; then
      local start_unit="../${unit_bn}.mount"
   else
      local start_unit="../${unit_bn}.automount"
      mk_automount_unit $what $where $target
   fi
   cat << EOF > "${svc_dir}/${unit_bn}.mount"
[Unit]
Description=mount unit for $what
Documentation=file:///usr/lib/systemd/system-generators/dema-automount-generator

[Mount]
What=$what
Where=$where
Type=$fs
Options=$opts
TimeoutSec=10
EOF

   req="${svc_dir}/${target}.requires"
   mkdir -p "$req" && ln -sf "$start_unit" "$req"
   log " * $what => $where"
}



nfsopts="rw,nosuid,nodev,hard,intr,rsize=8192,wsize=8192,noauto,x-systemd.automount"

log "I got this arguments: $*"

log "Creating units for demas"
for i in $(seq 1 99); do
    what=dema$i:/localdisks
    where=/cluster/dema$i
    mk_mount_unit $what $where nfs "$nfsopts"
done


#### other NFS shares
log "Creating units for other NFS shares"
mk_mount_unit 134.96.30.184:/distribution/gentoo-amd64 / nfs ro

mk_mount_unit home-srv:/exports/raid/home /home                 nfs4 user=root,$nfsopts


### tmpfs mounts
log "Creating units for tmpfs mounts"
mk_mount_unit none /localdisks tmpfs mode=755


### bind mount
log "Create bind mount of rootfs"
mk_mount_unit / /rootfs none bind
