#!/usr/bin/ash

die() {
    echo "ERROR: $@"
    echo "Starting emergency shell"
    /bin/sh
}

run_hook() {
   DUMMY_MAC="00:10:4B:DC:82:6B"
   modprobe dummy

   cd /sys/class/net
   for dev in $( echo eth* | awk '{NF++;while(NF-->1)print $NF}') ; do
      # iterate over all devices, from the last to the first
      NEW_NAME="eth$(( ${dev#eth} + 1))"
      echo renaming $dev to $NEW_NAME
      nameif $NEW_NAME $(cat $dev/address) || die "failed to move device"
   done

   ifconfig dummy0 hw ether $DUMMY_MAC  || die "cant run ifconfig"
   nameif   eth0 $DUMMY_MAC || die "failed to execute nameif"
}

run_latehook() {
   # create something writeable
   /bin/mount -ttmpfs none /new_root/tmp || die
   /bin/mount -ttmpfs none /new_root/var || die

   echo "mounting configuration of `hostname` to /writeable/client_config"

   if nfsmount 134.96.30.183:/exports/raid/client/config/`hostname -s` /new_root/writeable/client_config ; then
      if ! sh /new_root/usr/local/client_config/have_permanent.sh  /new_root/writeable/client_config /new_root ; then
         echo "Skript failed, please inform admin... (waiting 60 sek before boot will continue)"
         sleep 60
      fi
   else
      echo "mounting failed, creating dummy config... please let admin know."
      /bin/mount -ttmpfs none /new_root/writeable/client_config || die
      sh /new_root/usr/local/client_config/have_nonpermanent.sh /new_root/writeable/client_config /new_root
      sleep 10
   fi
}
# vim: set ft=sh ts=4 sw=4 et:
